export interface BrandAttribute {
  adjective: string;
  icon: string;
}
export const brandAttributesData: BrandAttribute[] = [
  { adjective: 'active', icon: 'directions_run' },
  { adjective: 'adventurous', icon: 'explore' },
  { adjective: 'ambitious', icon: 'show_chart' },
  { adjective: 'approachable', icon: 'forum' },
  { adjective: 'authentic', icon: 'verified' },
  { adjective: 'bohemian', icon: 'brush' },
  { adjective: 'bold', icon: 'format_bold' },
  { adjective: 'brave', icon: 'shield' },
  { adjective: 'bright', icon: 'wb_sunny' },
  { adjective: 'bubbly', icon: 'mood' },
  { adjective: 'calm', icon: 'spa' },
  { adjective: 'candid',icon: 'photo_camera' },
  { adjective: 'carefree',icon: 'bubble_chart' },
  { adjective: 'careful', icon: 'security' },
  { adjective: 'innovative', icon: 'lightbulb_outline' },
  { adjective: 'dynamic', icon: 'bolt' },
  { adjective: 'sophisticated', icon: 'emoji_objects' },
  { adjective: 'friendly', icon: 'pets' },
  { adjective: 'energetic', icon: 'battery_charging_full' },
  { adjective: 'inspiring', icon: 'emoji_events' },
  { adjective: 'playful', icon: 'sports_esports' },
  { adjective: 'intuitive', icon: 'fingerprint' },
  { adjective: 'professional', icon: 'work_outline' },
  { adjective: 'quirky', icon: 'mood_bad' },
  { adjective: 'reliable', icon: 'verified_user' },
  { adjective: 'sleek', icon: 'drag_indicator' },
  { adjective: 'stylish', icon: 'style' },
  { adjective: 'trendy', icon: 'whatshot' },
  { adjective: 'trustworthy', icon: 'lock_outline' },
  { adjective: 'visionary', icon: 'remove_red_eye' },
  { adjective: 'welcoming', icon: 'home' },
  { adjective: 'whimsical', icon: 'waving_hand' },
  { adjective: 'youthful', icon: 'sports_soccer' },
  { adjective: 'zen', icon: 'spa' }
];
